### ISSUE TITLE
CMake build with Linux

### ISSUE THREAD

**Issue by waarmond** [LadybirdWebBrowser/ladybird#63]
After https://awesomekling.substack.com/p/forking-ladybird-and-stepping-down-serenityos I've though that such a system string check wouldn't be necessary. Error at config under ArchLinux:

```
CMake Error at CMakeLists.txt:15 (message):
  System name is not SerenityOS, this is unsupported.
```

**Comment by BertalanD** [comment]
That check in CMakeLists.txt no longer exists on `master` as of https://github.com/LadybirdWebBrowser/ladybird/commit/66d91fa08cac961007322f33dd1acef80c328a22. Please pull again.

**Comment by waarmond** [comment]
My error: I've had cloned https://github.com/awesomekling/ladybird !
