### ISSUE TITLE
can

### ISSUE THREAD

**Issue by wx-11** [LadybirdWebBrowser/ladybird#76]

**Comment by awesomekling** [comment]
I'm not sure what you're asking for exactly, but we are currently in the pre-alpha development stage. We are not ready to ship anything usable yet :)

**Comment by sin-ack** [comment]
Did you find any particular need for Docker when trying out the build process? IMHO, it would be a much better idea to minimize system-level dependencies (with something like Bazel or CMake's `FetchContent`) and "abandoning hope" and locking the build system to Docker.

**Comment by ADKaster** [comment]
For what it's worth, there is a devcontainer in the repo. It should be possible to use it to build the application with the VsCode devcontainers support. Or another IDE's support for that technology.
